// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYPbMsIvyjDGzkxrXU76eLGmd64bIRjiU',
    appId: '1:1011634766981:web:f875671f411bb5066b15ec',
    messagingSenderId: '1011634766981',
    projectId: 'sales-2fce0',
    authDomain: 'sales-2fce0.firebaseapp.com',
    databaseURL: 'https://sales-2fce0-default-rtdb.firebaseio.com',
    storageBucket: 'sales-2fce0.appspot.com',
    measurementId: 'G-E5B4HWXGD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqv6AW1M9tUmpTish5I8PwvANhLE6fBvM',
    appId: '1:1011634766981:android:d3f4f8c31ed5c6fb6b15ec',
    messagingSenderId: '1011634766981',
    projectId: 'sales-2fce0',
    databaseURL: 'https://sales-2fce0-default-rtdb.firebaseio.com',
    storageBucket: 'sales-2fce0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo5ILID1qFNcy0W0f_yW9izF8DiU75diU',
    appId: '1:1011634766981:ios:b91ec13de42f297f6b15ec',
    messagingSenderId: '1011634766981',
    projectId: 'sales-2fce0',
    databaseURL: 'https://sales-2fce0-default-rtdb.firebaseio.com',
    storageBucket: 'sales-2fce0.appspot.com',
    iosClientId: '1011634766981-t74scqriehhrklakjbn4hlih43uqmgjb.apps.googleusercontent.com',
    iosBundleId: 'com.example.salesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo5ILID1qFNcy0W0f_yW9izF8DiU75diU',
    appId: '1:1011634766981:ios:b91ec13de42f297f6b15ec',
    messagingSenderId: '1011634766981',
    projectId: 'sales-2fce0',
    databaseURL: 'https://sales-2fce0-default-rtdb.firebaseio.com',
    storageBucket: 'sales-2fce0.appspot.com',
    iosClientId: '1011634766981-t74scqriehhrklakjbn4hlih43uqmgjb.apps.googleusercontent.com',
    iosBundleId: 'com.example.salesApp',
  );
}
